앱별 모델링 작성 완료
wecode-bootcamp-korea/28-1st-MRMRZR-backend pull request #3
Opened 2021-12-28 09:26 UTC by Bruno-Jang

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [x] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- erd를 토대로 앱별 모델링 작성 완료

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 리뷰 내용 반영하여 앱별 모델링 작성 완료

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
 - 1대다, 다대다 관계에 따른 foreignkey, manytomanyfield 등의 적용이 헷갈렸습니다.

<br />

## :: 기타 질문 및 특이 사항
- price의 경우 원화를 쓰는데 decimal에서 decimal_places=2 를 해야할 필요가 있는지 질문 드립니다.

2021-12-28 12:36 UTC, Kang-kyunghun requested changes

2021-12-28 12:36 UTC, Kang-kyunghun commented on carts/models.py
> +    products_options = models.ForeignKey(Product, on_delete=models.CASCADE)
ForeignKey로 연결 된 곳이 Product가 맞나요??

2021-12-28 12:36 UTC, Kang-kyunghun commented on orders/models.py
> +
공백 하나 제거해 주세요.

2021-12-28 12:36 UTC, Kang-kyunghun commented on orders/models.py
> +    order_number = models.CharField(max_length=20)
보통 유니크한 넘버를 만들 때 uuid를 사용하는데, 장고에서 max_length 1이 몇 byte을 할당하는지 확인해보고 코멘트 달아 주세요

2021-12-28 12:59 UTC, Bruno-Jang commented on carts/models.py
> +    products_options = models.ForeignKey(Product, on_delete=models.CASCADE)
Product가 아니었습니다.. 잘못 썼네요 수정하겠습니다!

2021-12-29 02:09 UTC, Bruno-Jang commented on orders/models.py
> +    order_number = models.CharField(max_length=20)
https://files.slack.com/files-pri/TH0U6FBTN-F02RPUCN5QX/______________2021-12-29_00-00-37.png
우선 저희가 만들고 싶은 주문번호의 형태는 위의 사진과 같습니다. 그래서 만약 "YYMMDD - 임의의 문자열" 에 UUID4를 사용해서 DB에는 UUID 전체를 저장하고 view 단에서는 "20211228 - J021A1" UUID에서 indexing을 사용해서 보이는 부분에만 예시처럼 표현할 수 있을까요?
날짜로 제한을 했기에 indexing을 사용하더라도 중복의 가능성은 줄어들것 같고 실제 연결되는 UUID는 생성된 전체 UUID로 연결시켜서 해당 주문 조회가 가능할지 궁금합니다.
저희가 찾아본 바로는 문자열 중에 영어와 숫자는 1바이트를 차지하고 한글은 2바이트를 차지한다고 봤습니다.
그런데 UUID와 max_length 1이 차지하는 바이트를 물어보신 이유는 메모리의 작업의 효율성 또는 DB에 부하가 가는지 이런 부분때문에 물어보신게 맞으실까요?

2021-12-29 02:23 UTC, Kang-kyunghun commented on orders/models.py
> +    order_number = models.CharField(max_length=20)
해당 질문 했던 이유는
1. max_length의 의미를 알고 있는지 -> django에서 max_length는 byte보다 문자의 길이를 뜻합니다.
2. uuid 생성시 몇 글자가 생성 되는지 -> '-'을 포함하면 36자리의 숫자가 나오는데, 그러면 max_length=20은 모자르겠죠?
3. 요즘은 너무 비정상적인 메모리 할당이 아닌 이상 메모리의 여유가 있기 때문에 너무 딱 정확히 할당하지 않아도 된다고 생각합니다.

2021-12-29 02:24 UTC, Kang-kyunghun commented
LGTM~!!

2021-12-29 02:42 UTC, wsji91 commented on orders/models.py
> +    order_number = models.CharField(max_length=20)
빠른 리뷰 감사드립니다!

2021-12-29 05:24 UTC, merged