장바구니 앱 제품 추가 기능 구현중
wecode-bootcamp-korea/28-1st-MRMRZR-backend pull request #5
Opened 2022-01-02 04:25 UTC by Bruno-Jang

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 장바구니에 제품 추가, 수량 변경, 삭제 기능 및 조회

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 해당 제품의 id가 DB에 있는 데이터인지 조회 후 없으면 에러메세지 리턴

2. 해당 사이즈의 id가 DB에 있는 데이터인지 조회 후 없으면 에러메세지 리턴

3. 비정상적인 수량 데이터나 재고보다 많은 수량 입력시 에러메세지 리턴

4. 해당 유저의 카트에 해당 제품이 이미 있다면 수량만 변경하는 기능을 넣었는데
   다른 함수를 통해서 기능을 구현해야할지 현재 이 함수에서 기능 구현이 가능할지 고민됩니다.
   현재는 한번에 구현하려고 했는데 찾아보니 Patch라는 http 메소드를 통해서 구현할 수 있는것 같아서 더 찾아보고 질문드리겠습니다!

추가로 구현하고 싶은 기능
1. carts 앱/views.py 의 28번째 줄의 filter 사용시 데이터가 없어서 생길 수 있는 에러에 대해 except 처리해야할듯 싶습니다. 

2. 카트에 담긴 전체 제품 목록 조회하는 기능

3. 제품 수량 변경 및 삭제 기능

4. 추후에 로그인 인증은 데코레이터 작성해서 해결할 예정

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 우선 모델링을 저희가 직접 작성하긴 했지만 유저와 프로덕트 정도까지였고 장바구니와 오더 부분은 사실상 경훈님께서 해주신거라서 직접 view를 작성하면서 고민하게 되는 부분이 많았습니다.
- 분명 시간은 많이 들였는데 솔직히 발전한 부분을 느낄 수가 없어서 많이 아쉽습니다.. 회원가입과 로그인 부분은 좀 했던 부분을 그대로 한것이여서 그럴수 있기 때문에 이번에 장바구니 앱을 하면서 느끼고 있는 이 막막함을 잊을 수 없을 것 같습니다. 이 앱의 기능들을 구현한다면 그때는 성장 포인트를 찾을 수 있을것 같습니다.

<br />

## :: 기타 질문 및 특이 사항
- 현재 카트에 유저 1명당 제품이 하나밖에 안 들어가는 것 같습니다. 혹시나 유저와 카트의 관계가 1대1이여서 그런가 싶어서 찾아봤는데 그거는 문제가 없어보여서 어떤 식으로 해결방법을 찾아야할지 방향만 조금 알려주실 수 있다면 감사하겠습니다!
- 수량도 초기화가 안 되고 누적되고 있어서 이 문제를 해결하고 싶습니다... (우선 수량 문제부터 해결해야 같은 유저가 장바구니에 여러 제품을 담지 못 하는 문제를 해결할 수 있을것 같아서 기존 제품이 있을 경우 그 수량에 입력한 수량을 더할수 있도록 하려고 합니다.)
- 혹시 프론트와 실제로 통신을 할 때 맞추는 Key는 name이나 다른 속성보다는 id를 많이 쓰겠죠? 주석으로 달아놓기는 했지만 데이터의 양이 엄청 많아졌을 때 PK 값인 id와 name으로 filter나 get을 사용시 그 차이가 있는지 궁금해서 여쭤봅니다.

2022-01-02 12:23 UTC, Kang-kyunghun requested changes

2022-01-02 12:23 UTC, Kang-kyunghun commented on carts/views.py
> +            product = Product.objects.get(id=data['product_id'])    # id와 name 중에 name이 더 직관적이지만 우리가 데이터를 일일이 볼게 아니기도 하고 id가 조금이라도 메모리 공간?을 덜 잡아먹어서 id로 값을 보내는걸까?
id를 사용하는 이유는 id가 pk이기 때문입니다.
pk는 해당 데이터의 고유값이기 때문에 데이터를 특정 지을 때 사용합니다.
name은 얼마든지 중복값이 존재 할 수 있습니다.

2022-01-02 12:23 UTC, Kang-kyunghun commented on carts/views.py
> +                return JsonResponse({'result': 'SUCCESS'}, status=201)
이미 있는 제품에 대해 수량을 추가 하고 싶었던 것 같은데, 그럴 경우에 cart을 찾는 조건이 user가 아니고, product_option으로 찾아야 할 것 같습니다.

2022-01-02 12:23 UTC, Kang-kyunghun commented on carts/views.py
> +            size = Size.objects.get(id=data['size_id'])
```suggestion
            size_id = data['size_id']
```

2022-01-02 12:23 UTC, Kang-kyunghun commented on carts/views.py
> +            product_option = ProductOption.objects.filter(product_id=product, size_id=size)
```suggestion
            if not product.sizes.filter(size_id=size_id).exists():
                return JsonResponse({'message': 'INVALID_PRODUCT'}, status=400)
            
            product_option = product.sizes.get(size_id=size_id)
```
이미 불러온 product와 many to many 관계를 이용하여 product_option을 가져올 수 있을 것 같은데 한 번 shell에서 연습해보면 좋을 것 같아요.

2022-01-02 12:25 UTC, Kang-kyunghun commented
지금 보니까 Product model에 Many to Many field 선언한게 보이지 않네요. 추가하면 좋을 것 같아요.(ProductOption을 중간 테이블로 사용하는)

2022-01-05 04:41 UTC, Kang-kyunghun requested changes

2022-01-05 04:41 UTC, Kang-kyunghun commented on mrmrzara/urls.py
> +    path('shop', include('carts.urls')),
cart라고 해도 될 것 같은데, shop이라고 한 이유가 있을까요?

2022-01-05 04:42 UTC, Kang-kyunghun commented
전체적인 코드는 괜찮은 것 같네요.
원석님 디테일 코드랑 데코레이터 merge 되면 그 후에 merge 할게요.
그 사이에 delete 기능 추가하시면 같이 리뷰 하겠습니다.

2022-01-05 04:52 UTC, Bruno-Jang commented on mrmrzara/urls.py
> +    path('shop', include('carts.urls')),
실제로 ZARA 홈페이지 장바구니 url이 shop/cart로 되어있어서 그렇게 했습니다
cart로 바꿔도 괜찮습니다~!
delete 기능 구현해서 다시 push하겠습니다.

2022-01-05 07:07 UTC, Bruno-Jang commented
유저 로그인 인증을 데코레이터를 통해서 했는데 카트 제품 삭제 관련해서 69번째 줄에 user = request.user 라고 user라는 변수에 request.user 라는 값을 지정했는데 해당 변수를 그 아래에서 사용하지 않고 있는데 쓰는 의미가 있는걸까요? 우선 제가 decorator에 대해 잘 모르고 있어서 이에 대해 더 찾아보고 있겠습니다.

2022-01-05 09:05 UTC, Kang-kyunghun requested changes

2022-01-05 09:05 UTC, Kang-kyunghun commented on carts/views.py
> +        cart = Cart.objects.get(pk=cart_id)
```suggestion
        user = request.user
        cart = Cart.objects.get(pk=cart_id, user=user)
```
1. 장바구니를 확인 할 때 전달 받은 장바구니의 pk와 user를 동시에 조건을 넣어 주어야 해당 장바구니가 로그인 한 user의 장바구니인지 확인이 됩니다.(질문 주신 것에 대한 답변도 되었을 것 같네요.)
2. get을 통해 데이터를 가져오고 있으니 get을 사용 했을 때 발생할 수 있는 에러처리도 같이 해주세요.

2022-01-05 09:22 UTC, Bruno-Jang commented on carts/views.py
> +        cart = Cart.objects.get(pk=cart_id)
경훈님 답변 감사합니다! 수정 후 바로 PR하겠습니다.

2022-01-05 13:17 UTC, Kang-kyunghun requested changes

2022-01-05 13:17 UTC, Kang-kyunghun commented on carts/urls.py
> +]
```suggestion
    path('', CartView.as_view()),
    path('/<int:user_id>', CartView.as_view()),
    path('/<int:cart_id>', CartView.as_view()),
]
```
1. carts/list 가 최종 url이 되는데, carts로 충분히 cart들을 표현 합니다.
2. RESTful 규칙에 의거하면 url은 자원만 나타냅니다. 행위 즉 동사는 http method로 표시합니다. 따라서 delete는 지워주세요.

2022-01-05 13:17 UTC, Kang-kyunghun commented on carts/views.py
> +from users.utils     import LogInDecorator
```suggestion
from users.utils     import login_decorator
```
원석님 피드백에 올바른 함수명 컨벤션에 대해 피드백 남겨드렸습니다. 따라서 우경님도 다음과 같이 바꾸시면 될 것 같습니다.

2022-01-05 15:41 UTC, Bruno-Jang commented on carts/urls.py
> +]
의미가 중복되는 url 삭제 및 HTTP Method나 동사표현이 url에 들어가면 안 된다는 것을 배웠습니다.
경훈님 RESTful API 규칙을 보니 제가 한게 딱 잘못된 사례로 나와있네요 감사합니다!

2022-01-05 16:01 UTC, Bruno-Jang commented on carts/views.py
> +from users.utils     import LogInDecorator
경훈님 덕분에 듣기만 하던 camel case, Pascal case, snake case에 대해 익힐 수 있었습니다.
수정한 후에 PR했습니다.

2022-01-06 05:14 UTC, Kang-kyunghun commented
LGTM!!

2022-01-06 05:14 UTC, merged