[products app] ProductListView
wecode-bootcamp-korea/28-1st-MRMRZR-backend pull request #8
Opened 2022-01-03 07:00 UTC by sxxk2

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

전체 프로덕트를 호출 후
필터와 소트기능을 사용할 수 있도록 로직을 구성중.

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)

result에 기본적인 데이터만 담아서 보내줍니다.

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

models.py기준 각각 다른class에 있는 데이터들을 views 로직을 사용 중 result에 같이 담아서 보내주는게 어려웠습니다..

<br />

## :: 기타 질문 및 특이 사항
- 필터와 소트가..아직도 애매합니다.

2022-01-03 10:25 UTC, sxxk2 commented
order_by를 사용해서 가격 오름,내림차순을 구현해봤고
통신해볼 해수님에게 key와 value값을 공유했습니다.

2022-01-05 13:12 UTC, Kang-kyunghun requested changes

2022-01-05 13:12 UTC, Kang-kyunghun commented on .vscode/extensions.json
> +}
불필요한 파일입니다. 제거하고 올려주세요.

2022-01-05 14:30 UTC, sxxk2 commented on .vscode/extensions.json
> +}
제거후 다시 push 했습니다.

2022-01-05 14:30 UTC, sxxk2 commented
conflict 나름대로 잡아봤는데 확인 부탁드립니다.

2022-01-06 05:28 UTC, Kang-kyunghun commented
LGTM

2022-01-06 05:28 UTC, merged