로그인 데코레이터 생성
wecode-bootcamp-korea/28-1st-MRMRZR-backend pull request #9
Opened 2022-01-05 06:35 UTC by wsji91

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 아이디, 비밀번호 입력창을 사용한 로그인 기능 구현 (예시)

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 로그인 데코레이터 생성
- 데코레이터를 통한 토큰 부여를 통한 유저에 대한 인증/인가 작업

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 13,14 라인과 24,25라인의 큰 차이를 모르겠는데, 13-14라인은 없애도 될까 싶은 생각이 듭니다.
<br />

## :: 기타 질문 및 특이 사항
- 19라인에서 'user_id'를 키로 꺼내는데, 여기서 user_id는 User Class에서 저절로 생긴 유저의 id 값(숫자)이겠죠..?
- user.id 와 user_id 등... 갑자기 헷갈립니다ㅜㅜ

2022-01-05 09:01 UTC, Kang-kyunghun requested changes

2022-01-05 09:01 UTC, Kang-kyunghun commented on users/utils.py
> +    @wraps(func)
해당 데코레이터를 붙이신 이유가 무엇인가요?

2022-01-05 09:01 UTC, Kang-kyunghun commented on users/utils.py
> +            request.user = User.objects.get(id = decoded_token['user_id'])
```suggestion
        try:
            if not request.headers.get('Authorization'):
                return JsonResponse({'message' : 'NO_TOKEN'}, status = 403)
                
            access_token  = request.headers.get('Authorization', None)
            decoded_token = jwt.decode(access_token, SECRET_KEY, ALGORITHM)
            request.user  = User.objects.get(id = decoded_token['user_id'])
```
1. 처음 if 문도 try이 안에 있는 것이 조금 더 가독성이 좋아 보이네요.
2. = 기준으로 정렬 해주세요.

2022-01-05 09:03 UTC, wsji91 commented on users/utils.py
> +    @wraps(func)
> 해당 데코레이터를 붙이신 이유가 무엇인가요?

내장함수의 속성을 잃지 않기 위해서 붙이는거라고 하여 붙여보았습니다. 이 경우에는 필요없는 걸까요?

2022-01-05 13:10 UTC, Kang-kyunghun requested changes

2022-01-05 13:10 UTC, Kang-kyunghun commented on users/utils.py
> +def LogInDecorator(func):
```suggestion
def login_decorator(func):
```
함수명은 스네이크 케이스로 작성하셔야 합니다.
기존에 작성했던 방법은 class 이름 지으실 때 사용하는 방법입니다.

2022-01-06 01:13 UTC, wsji91 commented on users/utils.py
> +def LogInDecorator(func):
넵 반영하였습니다!

2022-01-06 05:12 UTC, Kang-kyunghun commented
LGTM

2022-01-06 05:13 UTC, merged